  
  - name: Update
    apt: update_cache=yes   

  - name: Installing Redis
    apt: name=redis-server state=latest

    notify:
    - restart redis.service 

  - name: Restart Redis Server
    service: name=redis state=restarted enabled=yes
  
  - name: pull an image
    docker_image:
      name: badmusanu/tradebyte

  - name: deploy nginx docker container
    docker_container:
      image: tradebyte
      name: tradebyte
      state: started
      auto_remove: true
      ports:
        - "8080:80"

