version: 2.1

jobs:
  test:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - run:
          name: application testing
          command: |
            python tests/test.py


  deploy:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["b6:f9:09:aa:2d:0c:87:a0:3c:77:5a:4c:1a:3b:23:48"] 
      
      - run:
          name: Install Ansible and Docker
          command: |
            sudo apt update
            sudo apt install apt-transport-https ca-certificates curl software-properties-common
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
            sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
            apt-cache policy docker-ce
            sudo apt install docker-ce
            sudo apt install ansible
            
      - run:
          name: build application
          command: |
            docker build -t badmusanu/tradebyte .
            docker push badmusanu/tradebyte 

      - run:
          name: Run Playbook and Configure server
          command: |
            ansible-playbook -i .circleci/ansible/inventory.txt .circleci/ansible/configure-server.yml        

          
workflows:
  default:
    jobs:
      - test
      - deploy:
          requires: [test]