version: 2.1

jobs:
  test:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - run:
          name: application testing
          command: |
            python tests/test.py


  deploy:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - run:
          name: build application
          command: |

            echo $DOCKERHUB_PASS | docker login -u $DOCKERHUB_USER --password-stdin
            docker build -t badmusanu/tradebyte .
            docker push badmusanu/tradebyte 
          
workflows:
  default:
    jobs:
      - test
      - deploy:
          requires: [test]